# This file provides instructions for packaging.

`package-compute`
	perl_version_from m`package::compute`;
	version_from      m`package::compute`;
	readme_from       m`package::compute`;
	requires          p`B::Hooks::Parser`;
	test_requires     p`Test::More 0.61`;
	.

